//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartsheduler_Api.MYDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidayinformation
    {
        public int serial { get; set; }
        public string holiday { get; set; }
        public string date { get; set; }
        public string day { get; set; }
    }
}
