//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartsheduler_Api.MYDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Smart_SchedulerEntities : DbContext
    {
        public Smart_SchedulerEntities()
            : base("name=Smart_SchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<branchID> branchIDs { get; set; }
        public DbSet<holidayinformation> holidayinformations { get; set; }
        public DbSet<notesinformation> notesinformations { get; set; }
        public DbSet<noticeinformation> noticeinformations { get; set; }
        public DbSet<placementinformation> placementinformations { get; set; }
        public DbSet<profileinformation> profileinformations { get; set; }
        public DbSet<resultinformation> resultinformations { get; set; }
        public DbSet<subjectinformation> subjectinformations { get; set; }
        public DbSet<timetableinformation> timetableinformations { get; set; }
    }
}
