//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartsheduler_Api.MYDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class notesinformation
    {
        public int rowid { get; set; }
        public string Enno { get; set; }
        public string Title { get; set; }
        public string notes { get; set; }
        public string date { get; set; }
    }
}
