//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartsheduler_Api.MYDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class profileinformation
    {
        public int rowid { get; set; }
        public string Enno { get; set; }
        public string name { get; set; }
        public string semester { get; set; }
        public string branch { get; set; }
        public string mobile { get; set; }
        public string Emailid { get; set; }
        public string password { get; set; }
    }
}
