# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatFirebase' do
  
   use_frameworks!
   pod 'Firebase/Storage'
   pod 'Firebase/AdMob'
   pod 'Firebase/Auth'
   pod 'Firebase/Crash'
   pod 'Firebase/Database'
   pod 'Firebase/RemoteConfig'
 
end
